#!/bin/sh
set -e
SERVICE="watch_and_copy.service"
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
    # Active le service au démarrage
    systemctl enable "$SERVICE"

    # S'il tourne déjà => restart
    # Sinon => start
    if systemctl is-active --quiet "$SERVICE"; then
       systemctl restart "$SERVICE"
    else
       if [ -f /etc/watch_and_copy/config.json ]; then
          systemctl start "$SERVICE"
    fi
fi

exit 0